input_mode: "api"
logger:
  level: "info"
  save_log: False
file_service:
  cv:
    file_name: "example_cv_small_1026.json"
    folder_path: "storage/cv"
  jr:
    file_name: "example_jr_small_complex_5.json"
    folder_path:  "storage/jr"
jr_chunk:
  chunk_size: 1
  stride: 1
embedding:
  batch_size: 4096
  device: "cuda"
  model: "sentence-transformers/all-MiniLM-L6-v2"
retrieval:
  query_top_k: 3
  component_top_k: 2
  threshold: 0.3
  filter_below_threshold: False
evaluation:
  evidence_mul : 1.0
  capability_mul : 1.0
  responsibility_mul: 1.0
llm:
  model: "gpt-4o-mini"
  max_retry: 2
  timeout: 30
  prompt_tokens_per_1M: 0.15
  completions_tokens_per_1M: 0.60
  usd_to_idr: 17200
